import { existsSync, writeFileSync } from "node:fs";
import { execFile } from "node:child_process";
import { join } from "node:path";
import { logError } from "./storage.mjs";

const DATA_GITIGNORE = `# Auto-generated by copilot-brag-sheet
# Only track meaningful records, not session noise

# Session records (high volume, auto-generated)
sessions/

# Runtime files
errors.log
*.lock
*.tmp.*
`;

const DATA_README = `# Work Log Data

This directory is managed by [copilot-brag-sheet](https://github.com/vidhartbhatia/copilot-brag-sheet).

- \`entries/\` — Your saved work accomplishments
- \`config.json\` — Your preferences
- \`work-log.md\` — Generated work log (regenerate anytime)

Session records are auto-excluded from git (too noisy).
`;

/**
 * Create a git runner that wraps execFile for testability.
 * @param {Function} [impl] - execFile implementation (for mocking)
 * @returns {Function} (args, cwd) => Promise<{ code, stdout, stderr }>
 */
export function createGitRunner(impl) {
  const run = impl || execFile;
  return (args, cwd) =>
    new Promise((resolve) => {
      run("git", args, { cwd, timeout: 15000, windowsHide: true }, (err, stdout, stderr) => {
        resolve({
          code: err?.code === "ENOENT" ? -1 : (err?.status ?? err?.code ?? 0),
          stdout: (stdout || "").trim(),
          stderr: (stderr || "").trim(),
        });
      });
    });
}

/**
 * Initialize a git repo in the data directory if not already present.
 * Creates .gitignore and README.md for a clean repo experience.
 * @param {string} dataDir
 * @param {Function} [runGit] - Git command runner (for testing)
 * @returns {Promise<boolean>} true if repo exists or was created
 */
export async function ensureGitRepo(dataDir, runGit) {
  if (!dataDir) return false;
  if (existsSync(join(dataDir, ".git"))) return true;

  const git = runGit || createGitRunner();

  const initResult = await git(["init", "-b", "main"], dataDir);
  if (initResult.code !== 0) {
    logError(dataDir, "git-backup:init", initResult.stderr || `exit ${initResult.code}`);
    return false;
  }

  // Create .gitignore and README for a clean repo
  try {
    writeFileSync(join(dataDir, ".gitignore"), DATA_GITIGNORE);
    writeFileSync(join(dataDir, "README.md"), DATA_README);
  } catch { /* best effort */ }

  // Initial commit with repo scaffolding
  await git(["add", "-A"], dataDir);
  await git(["commit", "-m", "init: copilot-brag-sheet data"], dataDir);
  return true;
}

/**
 * Add a remote to the data dir git repo.
 * @param {string} dataDir
 * @param {string} remoteUrl
 * @param {Function} [runGit]
 * @returns {Promise<boolean>}
 */
export async function addRemote(dataDir, remoteUrl, runGit) {
  if (!dataDir || !remoteUrl) return false;
  const git = runGit || createGitRunner();
  const result = await git(["remote", "add", "origin", remoteUrl], dataDir);
  return result.code === 0;
}

/**
 * Check if a remote is configured in the data dir.
 * @param {string} dataDir
 * @param {Function} [runGit]
 * @returns {Promise<boolean>}
 */
export async function hasRemote(dataDir, runGit) {
  if (!dataDir) return false;
  const git = runGit || createGitRunner();
  const result = await git(["remote", "get-url", "origin"], dataDir);
  return result.code === 0 && result.stdout.length > 0;
}

/**
 * Commit changes in the data directory and optionally push.
 * The data dir itself is the git repo (local-first design).
 * Never throws — logs errors to errors.log.
 *
 * @param {object} options
 * @param {string} options.dataDir - Data directory (is the git repo)
 * @param {{ enabled: boolean, push?: boolean }} options.gitConfig
 * @param {Function} [options.runGit] - Git command runner (for testing)
 * @returns {Promise<{ success: boolean, action: string }>}
 */
export async function backupToGit({ dataDir, gitConfig, runGit }) {
  const noop = { success: true, action: "skipped" };

  try {
    if (!gitConfig?.enabled || !dataDir) return noop;
    if (!existsSync(join(dataDir, ".git"))) return noop;

    const git = runGit || createGitRunner();

    // Stage all changes
    const addResult = await git(["add", "-A"], dataDir);
    if (addResult.code !== 0) {
      logError(dataDir, "git-backup:add", addResult.stderr || `exit ${addResult.code}`);
      return { success: false, action: "add-failed" };
    }

    // Check for staged changes
    const diffResult = await git(["diff", "--cached", "--quiet"], dataDir);
    if (diffResult.code === 0) {
      return { success: true, action: "no-changes" };
    }

    // Commit
    const date = new Date().toISOString().split("T")[0];
    const commitResult = await git(
      ["commit", "-m", `auto: work log update ${date}`],
      dataDir,
    );
    if (commitResult.code !== 0) {
      logError(dataDir, "git-backup:commit", commitResult.stderr || `exit ${commitResult.code}`);
      return { success: false, action: "commit-failed" };
    }

    // Push if enabled and remote exists
    if (gitConfig.push === true) {
      const remoteExists = await hasRemote(dataDir, git);
      if (remoteExists) {
        // Pull --rebase to absorb remote changes, then push
        await git(["pull", "--rebase", "--quiet"], dataDir);
        git(["push", "--quiet"], dataDir).then((pushResult) => {
          if (pushResult.code !== 0) {
            logError(dataDir, "git-backup:push", pushResult.stderr || `exit ${pushResult.code}`);
          }
        }).catch((err) => {
          logError(dataDir, "git-backup:push", err);
        });
      }
    }

    return { success: true, action: "committed" };
  } catch (err) {
    logError(dataDir, "git-backup", err);
    return { success: false, action: "error" };
  }
}
