const GENERATED_BANNER = [
  "<!-- Generated by Copilot Brag Sheet — edits may be overwritten -->",
  "<!-- Regenerate with: \"generate my work log\" in Copilot CLI -->"
];

const START_MARKER = "<!-- WEEKLY_ENTRIES_START — do not remove this marker -->";
const END_MARKER = "<!-- WEEKLY_ENTRIES_END — do not remove this marker -->";

const DEFAULT_CATEGORIES = [
  { id: "pr", emoji: "🚀", label: "PRs & Features" },
  { id: "bugfix", emoji: "🐛", label: "Bug Fixes" },
  { id: "infrastructure", emoji: "🏗️", label: "Infrastructure" },
  { id: "investigation", emoji: "🔍", label: "Investigation" },
  { id: "collaboration", emoji: "🤝", label: "Collaboration" },
  { id: "tooling", emoji: "🔧", label: "Tooling & DX" },
  { id: "oncall", emoji: "🚨", label: "On-Call" },
  { id: "design", emoji: "📐", label: "Design" },
  { id: "documentation", emoji: "📝", label: "Documentation" }
];

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export function weekOf(dateStr) {
  const date = new Date(dateStr);
  if (Number.isNaN(date.getTime())) {
    throw new Error("Invalid date");
  }

  const utcDate = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
  const day = utcDate.getUTCDay();
  const diff = day === 0 ? -6 : 1 - day;
  utcDate.setUTCDate(utcDate.getUTCDate() + diff);
  return formatDate(utcDate);
}

export function renderMarkdown(records = [], options = {}) {
  const filteredRecords = filterRecords(records, options);
  const includeSessionLog = options.includeSessionLog ?? options.config?.output?.includeSessionLog ?? false;
  const categoryMeta = buildCategoryMeta(options.config);
  const weekMap = new Map();

  for (const record of filteredRecords) {
    const weekKey = weekOf(record.timestamp);
    if (!weekMap.has(weekKey)) {
      weekMap.set(weekKey, { categories: new Map(), sessions: [] });
    }

    const bucket = weekMap.get(weekKey);

    if (record.type === "session") {
      bucket.sessions.push(record);
    }

    if (record.category) {
      if (!bucket.categories.has(record.category)) {
        bucket.categories.set(record.category, []);
      }

      bucket.categories.get(record.category).push(record);
    }
  }

  const lines = [...GENERATED_BANNER, "", "# Work Impact Log", "", START_MARKER, ""];
  const orderedWeeks = [...weekMap.keys()].sort((a, b) => b.localeCompare(a));

  for (const weekKey of orderedWeeks) {
    const bucket = weekMap.get(weekKey);
    lines.push(`## Week of ${weekKey}`, "");

    for (const categoryId of categoryMeta.order) {
      const items = bucket.categories.get(categoryId) || [];
      if (items.length === 0) {
        continue;
      }

      const category = categoryMeta.map.get(categoryId) || { emoji: "•", label: categoryId };
      lines.push(`### ${category.emoji} ${category.label}`);

      for (const item of items.sort(sortNewestFirst)) {
        lines.push(formatBullet(item));
      }

      lines.push("");
    }

    // Render entries that have no category (or unrecognized category)
    const uncategorized = filteredRecords.filter(
      (r) => r.type !== "session" && !categoryMeta.map.has(r.category) && weekOf(r.timestamp) === weekKey,
    );
    if (uncategorized.length > 0) {
      lines.push("### 📌 Other");
      for (const item of uncategorized.sort(sortNewestFirst)) {
        lines.push(formatBullet(item));
      }
      lines.push("");
    }

    if (includeSessionLog) {
      const sessions = bucket.sessions.slice().sort(sortNewestFirst);
      if (sessions.length > 0) {
        lines.push("### 📝 Session Activity Log");
        lines.push("| Time | Summary | Repo | Files |");
        lines.push("|------|---------|------|-------|");

        for (const session of sessions) {
          lines.push(formatSessionRow(session));
        }

        lines.push("");
      }
    }
  }

  lines.push(END_MARKER);
  return lines.join("\n");
}

export function renderReviewSummary(records = [], options = {}) {
  const weeks = options.weeks ?? 4;
  const now = new Date();
  const startOfCurrentWeek = new Date(`${weekOf(now.toISOString())}T00:00:00.000Z`);
  startOfCurrentWeek.setUTCDate(startOfCurrentWeek.getUTCDate() - ((weeks - 1) * 7));

  return renderMarkdown(records, {
    ...options,
    dateRange: {
      since: startOfCurrentWeek.toISOString(),
      until: now.toISOString()
    }
  });
}

function filterRecords(records, options) {
  const categories = Array.isArray(options.categories) ? new Set(options.categories) : null;
  const since = options.dateRange?.since ? new Date(options.dateRange.since) : null;
  const until = options.dateRange?.until ? new Date(options.dateRange.until) : null;

  return (Array.isArray(records) ? records : []).filter((record) => {
    if (!record?.timestamp) {
      return false;
    }

    const timestamp = new Date(record.timestamp);
    if (Number.isNaN(timestamp.getTime())) {
      return false;
    }

    if (since && timestamp < since) {
      return false;
    }

    if (until && timestamp > until) {
      return false;
    }

    if (categories && record.category && !categories.has(record.category)) {
      return false;
    }

    if (categories && !record.category && record.type !== "session") {
      return false;
    }

    return true;
  });
}

function buildCategoryMeta(config) {
  const map = new Map();
  const order = [];

  for (const category of DEFAULT_CATEGORIES) {
    map.set(category.id, category);
    order.push(category.id);
  }

  for (const category of config?.categories || []) {
    if (!category?.id) {
      continue;
    }

    map.set(category.id, {
      id: category.id,
      emoji: category.emoji || "•",
      label: category.label || category.id
    });

    if (!order.includes(category.id)) {
      order.push(category.id);
    }
  }

  return { map, order };
}

function formatBullet(record) {
  const summary = record.summary || "(no summary)";
  const prefix = record.repo ? `[${record.repo}] ` : "";
  const impact = record.impact ? ` — ${record.impact}` : "";
  return `- **${prefix}${summary}**${impact}`;
}

function formatSessionRow(record) {
  const time = formatTableTime(record.timestamp);
  const summary = escapePipes(record.summary || "");
  const repo = escapePipes(record.repo || "");
  const files = String(
    new Set([...(record.filesEdited || []), ...(record.filesCreated || [])]).size
  );

  return `| ${time} | ${summary} | ${repo} | ${files} |`;
}

function formatTableTime(timestamp) {
  const date = new Date(timestamp);
  return `${MONTHS[date.getUTCMonth()]} ${date.getUTCDate()} ${String(date.getUTCHours()).padStart(2, "0")}:${String(date.getUTCMinutes()).padStart(2, "0")}`;
}

function escapePipes(value) {
  return String(value).replace(/\|/g, "\\|");
}

function sortNewestFirst(left, right) {
  return new Date(right.timestamp).getTime() - new Date(left.timestamp).getTime();
}

function formatDate(date) {
  return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}-${String(date.getUTCDate()).padStart(2, "0")}`;
}
